# Generated by Django 4.0.5 on 2022-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=15)),
                ('car_number', models.CharField(max_length=15, unique=True)),
                ('kakao_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
