# Generated by Django 4.0.5 on 2022-07-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=15)),
                ('car_number', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('kakao_id', models.BigIntegerField(null=True)),
                ('car_name', models.CharField(max_length=50)),
                ('trim', models.CharField(max_length=50)),
                ('body_shape', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('model_year', models.CharField(max_length=50)),
                ('first_registration_year', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('factory_price', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_phone_number', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=15)),
                ('car_number', models.CharField(max_length=15, unique=True)),
                ('car_name', models.CharField(max_length=50)),
                ('trim', models.CharField(max_length=50)),
                ('body_shape', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('model_year', models.CharField(max_length=50)),
                ('first_registration_year', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('factory_price', models.BigIntegerField()),
                ('kakao_id', models.BigIntegerField()),
                ('sunroof', models.BooleanField()),
                ('navigation', models.BooleanField()),
                ('ventilation_seat', models.BooleanField()),
                ('heated_seat', models.BooleanField()),
                ('electric_seat', models.BooleanField()),
                ('smart_key', models.BooleanField()),
                ('leather_seat', models.BooleanField()),
                ('electric_folding_mirror', models.BooleanField()),
                ('accident_status', models.BooleanField()),
                ('spare_key', models.IntegerField()),
                ('wheel_scratch', models.IntegerField()),
                ('outer_plate_scratch', models.IntegerField()),
                ('other_maintenance_repair', models.TextField()),
                ('other_special', models.TextField()),
                ('quote_requested', models.DateTimeField()),
                ('dealer_assigned', models.DateTimeField()),
                ('dealer_consulting', models.DateTimeField()),
                ('selling_requested', models.DateTimeField()),
                ('selling_completed', models.DateTimeField()),
                ('termination', models.DateTimeField()),
                ('process_state', models.CharField(max_length=100)),
                ('dealer_name', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=20)),
                ('consulting_content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'db_table': 'transaction_histories',
            },
        ),
        migrations.CreateModel(
            name='InsuranceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'db_table': 'insurance_histories',
            },
        ),
    ]
