# Generated by Django 4.0.5 on 2022-07-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=15)),
                ('car_number', models.CharField(max_length=15, unique=True)),
                ('kakao_id', models.BigIntegerField(null=True)),
                ('car_name', models.CharField(max_length=50, null=True)),
                ('trim', models.CharField(max_length=50, null=True)),
                ('body_shape', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('model_year', models.CharField(max_length=50, null=True)),
                ('first_registration_year', models.CharField(max_length=50, null=True)),
                ('engine', models.CharField(max_length=50, null=True)),
                ('transmission', models.CharField(max_length=50, null=True)),
                ('manufacturer', models.CharField(max_length=50, null=True)),
                ('factory_price', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'db_table': 'transaction_histories',
            },
        ),
        migrations.CreateModel(
            name='InsuranceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'db_table': 'insurance_histories',
            },
        ),
    ]
