# Generated by Django 4.0.4 on 2022-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=15)),
                ('car_number', models.CharField(max_length=15, unique=True)),
                ('car_name', models.CharField(max_length=50, null=True)),
                ('trim', models.CharField(max_length=50, null=True)),
                ('body_shape', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('model_year', models.CharField(max_length=50, null=True)),
                ('first_registration_year', models.CharField(max_length=50, null=True)),
                ('engine', models.CharField(max_length=50, null=True)),
                ('transmission', models.CharField(max_length=50, null=True)),
                ('manufacturer', models.CharField(max_length=50, null=True)),
                ('factory_price', models.BigIntegerField(null=True)),
                ('kakao_id', models.BigIntegerField(null=True)),
                ('sunroof', models.BooleanField()),
                ('navigation', models.BooleanField()),
                ('ventilation_seat', models.BooleanField()),
                ('heated_seat', models.BooleanField()),
                ('electric_seat', models.BooleanField()),
                ('smart_key', models.BooleanField()),
                ('leather_seat', models.BooleanField()),
                ('electric_folding_mirror', models.BooleanField()),
                ('accident_status', models.BooleanField()),
                ('spare_key', models.IntegerField()),
                ('wheel_scratch', models.IntegerField()),
                ('outer_plate_scratch', models.IntegerField()),
                ('other_maintenance_repair', models.TextField()),
                ('other_special', models.TextField()),
                ('quote_requested', models.DateTimeField(null=True)),
                ('dealer_assigned', models.DateTimeField(null=True)),
                ('dealer_consulting', models.DateTimeField(null=True)),
                ('selling_requested', models.DateTimeField(null=True)),
                ('selling_completed', models.DateTimeField(null=True)),
                ('termination', models.DateTimeField(null=True)),
                ('process_state', models.CharField(max_length=100, null=True)),
                ('dealer_name', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='phone_number',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
