# Generated by Django 4.0.4 on 2022-07-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_completion_car_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completion',
            old_name='phone_number',
            new_name='user_phone_number',
        ),
    ]
