# Generated by Django 4.0.4 on 2022-07-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_phone_number_completion_user_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Completion',
            new_name='CarCompletion',
        ),
    ]
