# Generated by Django 4.0.4 on 2022-07-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_completion_carcompletion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarCompletion',
            new_name='Completion',
        ),
    ]
