# Generated by Django 4.0.5 on 2022-07-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mileage', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('sunroof', models.BooleanField(default=False)),
                ('navigation', models.BooleanField(default=False)),
                ('ventilation_seat', models.BooleanField(default=False)),
                ('heated_seat', models.BooleanField(default=False)),
                ('electric_seat', models.BooleanField(default=False)),
                ('leather_seat', models.BooleanField(default=False)),
                ('smart_key', models.BooleanField(default=False)),
                ('electric_folding_mirror', models.BooleanField(default=False)),
                ('accident_status', models.TextField(null=True)),
                ('spare_key', models.IntegerField(default=0)),
                ('wheel_scratch', models.IntegerField(default=0)),
                ('outer_plate_scratch', models.IntegerField(default=0)),
                ('other_maintenance_repair', models.TextField(null=True)),
                ('other_special', models.TextField(null=True)),
                ('process_state', models.CharField(max_length=100, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'db_table': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='EstimateCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_info', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.estimate')),
            ],
            options={
                'db_table': 'estimate_car_images',
            },
        ),
    ]
