# Generated by Django 4.0.5 on 2022-07-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='accident_status',
            field=models.TextField(),
        ),
    ]
