# Generated by Django 4.0.5 on 2022-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_alter_estimatecarimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatecarimage',
            name='image_info',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
