# Generated by Django 4.0.5 on 2022-07-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimates', '0001_initial'),
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_requested', models.DateTimeField(null=True)),
                ('dealer_assigned', models.DateTimeField(null=True)),
                ('dealer_consulting', models.DateTimeField(null=True)),
                ('selling_requested', models.DateTimeField(null=True)),
                ('selling_completed', models.DateTimeField(null=True)),
                ('termination', models.DateTimeField(null=True)),
                ('process_state', models.CharField(max_length=100, null=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.estimate')),
            ],
            options={
                'db_table': 'sales_process',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('read', models.BooleanField()),
                ('sales_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.salesprocess')),
            ],
            options={
                'db_table': 'user_notifications',
            },
        ),
        migrations.CreateModel(
            name='QuoteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer_assign', models.BooleanField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.branch')),
                ('sales_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.salesprocess')),
            ],
            options={
                'db_table': 'quote_notifications',
            },
        ),
    ]
