# Generated by Django 4.0.5 on 2022-07-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='content',
            new_name='content',
        ),
    ]
