# Generated by Django 4.0.4 on 2022-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprocess',
            name='process_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesprocess',
            name='dealer_assigned',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='salesprocess',
            name='dealer_consulting',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='salesprocess',
            name='quote_requested',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='salesprocess',
            name='selling_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='salesprocess',
            name='selling_requested',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='salesprocess',
            name='termination',
            field=models.DateTimeField(null=True),
        ),
    ]
