# Generated by Django 4.0.5 on 2022-07-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_name_usernotification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
